version: "3"
services:
  web:
    build: .docker
    links:
      - mysql
    volumes:
      - .:/src
    ports:
      - 80:80
    working_dir: /src
    command: apachectl -DFOREGROUND
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: foo
      MYSQL_DATABASE: monitoring
      MYSQL_USER: monitoring
      MYSQL_PASSWORD: monitoring
